### ISSUE TITLE
Wiki maintain access permission

### ISSUE THREAD

**Issue by arkiny** [DKGL/DKGL#11]
@Hongtae 님,

현재 위키 접근 허가가 없어서 위키 편집 진행을 할수 없습니다.

**Comment by arkiny** [comment]
이슈 티켓 보시고 권한주시면 틈틈히 dkscript에 는것 옮겨서 작성해두겠습니다.

**Comment by Hongtae** [comment]
권한은 넣은것 같은데 한번 테스트 해보시고 안되면 알려주세요..

이 방법이 맞는지 모르겠네요.
https://docs.github.com/en/communities/documenting-your-project-with-wikis/changing-access-permissions-for-wikis

**Comment by arkiny** [comment]
Permission 생긴것 확인했습니다! 감사합니다.
